// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkHku-Fec715iWzOUmEFmBxho4Ze5Ifuw',
    appId: '1:821078435729:web:f1c9650e4a9e547f729c30',
    messagingSenderId: '821078435729',
    projectId: 'blood-managment-df4e4',
    authDomain: 'blood-managment-df4e4.firebaseapp.com',
    databaseURL: 'https://blood-managment-df4e4-default-rtdb.firebaseio.com',
    storageBucket: 'blood-managment-df4e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsDLLu5uSkwsmBrZPsJc5RHLUc5FhvwxM',
    appId: '1:821078435729:android:67d9c6c114528742729c30',
    messagingSenderId: '821078435729',
    projectId: 'blood-managment-df4e4',
    databaseURL: 'https://blood-managment-df4e4-default-rtdb.firebaseio.com',
    storageBucket: 'blood-managment-df4e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvI339UhZjd75SoLkkNX-0v7zsbPvMFfY',
    appId: '1:821078435729:ios:4b9d6530eda660a6729c30',
    messagingSenderId: '821078435729',
    projectId: 'blood-managment-df4e4',
    databaseURL: 'https://blood-managment-df4e4-default-rtdb.firebaseio.com',
    storageBucket: 'blood-managment-df4e4.appspot.com',
    iosBundleId: 'com.example.bloodBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvI339UhZjd75SoLkkNX-0v7zsbPvMFfY',
    appId: '1:821078435729:ios:4b9d6530eda660a6729c30',
    messagingSenderId: '821078435729',
    projectId: 'blood-managment-df4e4',
    databaseURL: 'https://blood-managment-df4e4-default-rtdb.firebaseio.com',
    storageBucket: 'blood-managment-df4e4.appspot.com',
    iosBundleId: 'com.example.bloodBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc5uUyVRADNgfo5JoD8NZwIazLBbUW9WE',
    appId: '1:821078435729:web:6bac37ed55e21588729c30',
    messagingSenderId: '821078435729',
    projectId: 'blood-managment-df4e4',
    authDomain: 'blood-managment-df4e4.firebaseapp.com',
    databaseURL: 'https://blood-managment-df4e4-default-rtdb.firebaseio.com',
    storageBucket: 'blood-managment-df4e4.appspot.com',
  );
}
